config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :home, only: [:index] do
    collection do
      get :search
      get :page_google_results
    end
  end

  resources :sessions do
    collection do
      get :terminate_account
    end

    member do
      get :select_account
    end
  end

  resources :accounts, only: [:destroy]

  get "/auth/twitter/callback" => "sessions#create"
  get '/auth/failure' => 'sessions#failure'
end

app/models/account.rb
class Account < ApplicationRecord
  serialize :graph_data

  def self.create_new_account(auth)
    self.find_or_create_by(nickname: auth['info']['nickname']) do |user|
      user.name = auth['info']['name']
      user.nickname = auth['info']['nickname']
      user.token = auth['credentials']['token']
      user.token_secret = auth['credentials']['secret']
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def destroy
    session[:graph_data] = nil
    if account = (Account.find(params[:id]) rescue nil)
      account.destroy
    end
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_account
    @account ||= session['account_id']
  end

  def destroy_account
    @account = nil
    session['account_id'] = nil
    session[:graph_data] = nil
  end

  def set_client
    if @client.present?
      @client
    else
      if account = Account.find_by(id: current_account)
        @client = Twitter::REST::Client.new do |config|
          config.consumer_key        = Credentials::APP_KEY
          config.consumer_secret     = Credentials::APP_SECRET
          config.access_token        = account.token
          config.access_token_secret = account.token_secret
        end
      else
        nil
      end
    end
  end

  def set_account
    @account = if current_account.present?
      Account.find_by(id: current_account)
    else
      nil
    end
  end

  def check_rate_limit
    if rate_limit_status = Twitter::REST::Request.new(@client, :get, 'https://api.twitter.com/1.1/application/rate_limit_status.json', resources: "application,search").perform
      if rate_limit_status[:resources][:application].values.first[:remaining] > 0
        any_remaining = rate_limit_status[:resources][:search].values.first[:remaining] > 0
        restart_time = Time.at(rate_limit_status[:resources][:search].values.first[:reset]) rescue ( (Time.now + 15.minutes) if @account.restart.blank?)
        @account.update_attributes(searchable: any_remaining, restart: any_remaining ? nil : restart_time)
        any_remaining
      else
        restart_time = Time.at(rate_limit_status[:resources][:search].values.first[:reset]) rescue ( (Time.now + 15.minutes) if @account.restart.blank?)
        @account.update_attributes(searchable: false, restart: restart_time)
        false
      end
    else
      restart_time = Time.at(rate_limit_status[:resources][:application].values.first[:reset]) rescue ( (Time.now + 15.minutes) if @account.restart.blank?)
      @account.update_attributes(searchable: false, restart: restart_time)
      false
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_client
  before_action :set_account

  def index
    @accounts = Account.all
    check_rate_limit if @client.present?
  end

  def search
    if @client.present?
      if check_rate_limit
        if params[:search].present?
          curr_time = Date.parse(params[:until]).strftime("%Y-%m-%d")
          prev_time = Date.parse(params[:since]).strftime("%Y-%m-%d")

          conditions = set_conditions(params)
          begin
            results = request_search(conditions)

            if results.present?
              @next_page = results.last[:id]
              results.shift(1) if params[:max_id].present?
              @total_results = results.count + params[:prev_count].to_i
              @graph_data = get_graph_data(results, prev_time, curr_time)

              if params[:graph_data].present?
                #prev_data = @account.graph_data
                prev_data = session[:graph_data]
                @graph_data.merge!(prev_data){ |key, graph_data_val, prev_data_val| graph_data_val + prev_data_val.to_i }
              else
                session[:graph_data] = nil
                #@account.update_attributes(graph_data: nil)
              end
              session[:graph_data] = @graph_data.select {|key, value| value != 0 }
              #@account.update_attributes(graph_data: @graph_data.select {|key, value| value != 0 })
            end
            @partial_results = results
          rescue Twitter::Error::TooManyRequests
            @error = "Twitter Error: Too Many Requests"
          end
          @google_results, @google_page = get_google_results(params[:search])
        else
          @error = "No Search Query"
        end
      else
        @google_results, @google_page = get_google_results(params[:search]) if params[:search].present?
        @error = "User Cannot Request Anymore. Wait 15 minutes"
      end
    else
      @error = "No Account Selected"
    end
  end

  def page_google_results
    @google_results, @google_page = get_google_results(params[:search], params[:start])
  end

  private

  def set_conditions(params)
    curr_time = Date.parse(params[:until]).strftime("%Y-%m-%d")
    prev_time = Date.parse(params[:since]).strftime("%Y-%m-%d")
    @user_query = "#{params[:search]} since:#{prev_time}"

    conditions = {}
    conditions[:result_type] = 'recent'
    conditions[:lang] = 'ja'
    conditions[:count] = 100
    conditions[:since_id] = params[:since_id] if params[:since_id].present?
    conditions[:max_id] = params[:max_id] if params[:max_id].present?
    conditions[:until] = curr_time
    conditions[:q] = @user_query
    conditions
  end

  def request_search(conditions)
    search_returns = Twitter::REST::Request.new(@client, :get, 'https://api.twitter.com/1.1/search/tweets.json', conditions).perform
    search_returns[:statuses]
  end

  def get_google_results(query, start=1)
    uri = URI('https://www.googleapis.com/customsearch/v1')
    params = { :q => query, :cx => Credentials::GOOGLE_KEY, :key => Credentials::GOOGLE_API_KEY, start: start.to_i }
    uri.query = URI.encode_www_form(params)

    res = Net::HTTP.get_response(uri)
    return JSON.parse(res.body), start
  end

  def get_graph_data(tweets, prev_time=nil, curr_time=nil)
    hours_hash = {}
    begin
      time_grouped = tweets.group_by{ |tweet| Time.parse(tweet[:created_at]).strftime('%Y-%m-%d %H') }
      time_grouped.each do |key, values|
        time_grouped_hour = Time.zone.parse(key).strftime('%Y-%m-%d %H:%M %z')
        hours_hash[time_grouped_hour] = values.count
      end

      prev_time = prev_time.to_datetime.beginning_of_day.to_i
      curr_time = (curr_time.to_datetime - 1.day).end_of_day.to_i
      (prev_time..curr_time).step(1.hour) do |hour_record|
        check_key = Time.at(hour_record).utc.strftime('%Y-%m-%d %H:%M %z')
        hours_hash[check_key] = 0 unless hours_hash.keys.include?(check_key)
      end
    rescue Twitter::Error::TooManyRequests
    end
    hours_hash
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    curr_account = Account.create_new_account(auth)
    session['account_id'] = curr_account.id
    redirect_to root_path
  end

  def terminate_account
    destroy_account
    redirect_to root_path
  end

  def select_account
    if account = Account.find(params[:id])
      session['account_id'] = account.id
    end
    redirect_to root_path
  end

  def failure
    flash['error'] = params['message']
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_bing_results.html.erb
<iframe src='https://www.bing.com/search?q=<%="#{CGI.escape(query)}"%>' id='bing-iframe' height='1500px' width='100%'>
</iframe>

app/views/home/_engine_results.html.erb
<div class='google-results'>
  <h3>Results from Google Custom Search</h3>
  <div class='google-results-container'>
    <%= render partial: 'home/google_results', locals: { google_results: google_results, google_page: google_page.to_i, query: query } %>
  </div>
</div>
<div class='bing-results'>
  <h3>Results from Bing Search</h3>
  <div class='bing-results-container'>
    <%= render partial: 'home/bing_results', locals: {query: query} %>
  </div>
</div>

app/views/home/_google_results.html.erb
<% if google_results.present? && google_results['items'].present? %>
  <% if google_page.to_i > 1 %>
    <%= link_to 'Prev', page_google_results_home_index_path(start: google_page.to_i - 10, search: query), remote: true %>
  <% end %>
  <% if google_results['queries']['nextPage'].present? %>
    <%= link_to 'Next', page_google_results_home_index_path(start: google_page.to_i + 10, search: query), remote: true %>
  <% end %>
  <br/><br/>

  <div class="list-group">
    <% google_results['items'].each_with_index do |result, index| %>
      <div id='google-result-<%= "#{index}" %>' class='list-group-item'>
        <%= link_to result['title'], result['link'] %><br/>
        <p><%= result['link'] %></p>
        <p><%= result['snippet'] %></p>
      </div>
    <% end %>
  </div>
<% else %>
No Results Found
<% end %>

app/views/home/_results.html.erb
<% tweets.each do |tweet| %>
  <div class='list-group-item item-<%= "#{tweet[:id]}"%>'>
    <h4 class="list-group-item-heading"><%= tweet[:user][:screen_name] %> - <%= Time.parse(tweet[:created_at]).strftime('%b %d, %Y %H:%M:%S') %></h4>
    <p class="list-group-item-text"><%= tweet[:text] %></p>
  </div>
<% end %>
</div>

app/views/home/_results_graph.html.erb
<%= line_chart data, xtitle: 'Time', ytitle: 'Number of Results', curve: false, library: {chart: {zoomType: 'x'}, subtitle: {text: "Click and drag in the graph area to zoom in"}}, title: 'Number of Resulting Tweets Over Time Period' %>
<h4>Number of Results: <%= count %></h4>

app/views/home/_results_nav.html.erb
<div class='center-block'>
<% if next_page.present? %>
<%= link_to "Load More", search_home_index_path(max_id: next_page, search: query, since: from_date, until: to_date, prev_count: count, graph_data: true), remote: true, class: 'btn btn-primary load-more' %>
<% end %>
</div>
<div class='clearfix'></div>

app/views/home/index.html.erb
Available Accounts:
<% if @accounts.present? %>
<table class='table table-striped table-bordered'>
  <thead>
    <th>Account Name</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% @accounts.each do |account_record|%>
      <tr>
        <td><%= account_record.nickname %></td>
        <td>
          <% unless @account == account_record%>
            <%= link_to "Select", select_account_session_path(account_record.id), class: 'btn btn-primary'%>
          <% end %>
          <%= link_to "Remove", account_path(account_record.id), method: 'delete', class: 'btn btn-danger'%>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<% end %>
<% if @account.present? %>
  <%= form_tag search_home_index_path, id: 'search-form', class: 'form-inline', method: :get, remote: true do %>
    <div class='form-group'>
      <%= label_tag :search %>
      <%= text_field_tag :search, nil, class: 'form-control', required: true %>
    </div>
    <div class='form-group'>
      <%= label_tag :since %>
      <%= date_field_tag(:since, (Date.today - 10.days), min: (Date.today - 10.days), max: (Date.today), required: true, class: 'form-control datepicker', readonly: true) %>
    </div>
    <div class='form-group'>
      <%= label_tag :until %>
      <%= date_field_tag(:until, (Date.today + 1.day), min: (Date.today - 9.days), max: (Date.today + 1.day), required: true, class: 'form-control datepicker', readonly: true) %>
    </div>
    <%= submit_tag "Search", id: 'search-btn', class: 'btn btn-primary', disabled: (!@account.searchable) %>
  <% end %>
  <div id='timer-container' data-time='<%= @account.restart.present? ? (@account.restart) : nil %>'></div>
<% end %>
<div id='results'>
  <div id='twitter-graph'></div>
  <div id='twitter-results'>
    <div class='list-group'>
    </div>
  </div>
  <div id='twitter-nav'></div>
  <div id='engine-results'></div>
</div>

<div class='loader hidden'></div>

app/views/home/page_google_results.js.erb
<% if @google_results.present? %>
  $('.google-results-container').empty().append("<%= escape_javascript(render partial: 'home/google_results', locals: { query: params[:search], google_results: @google_results, google_page: @google_page }) %>")
<% end %>
$('.loader').addClass('hidden');

app/views/home/search.js.erb
<% if @error.blank? %>
  <% if @partial_results.present? %>
    <% if @graph_data.present? %>
      $('#twitter-graph').empty().append("<%= escape_javascript(render partial: 'home/results_graph', locals: { data: @graph_data, count: @total_results } )%>");
    <% else %>
      $('#twitter-graph').empty();
    <% end %>
    $('#twitter-nav').empty().append("<%= escape_javascript(render partial: 'home/results_nav', locals: { next_page: @next_page, query: params[:search], count: @total_results, from_date: params[:since], to_date: params[:until] } ) %>");

    <% if params[:graph_data].present? %>
      $('#twitter-results .list-group').append("<%= escape_javascript(render partial: 'home/results', locals: { tweets: @partial_results } ) %>");
    <% else %>
      $('#twitter-results .list-group').empty().append("<%= escape_javascript(render partial: 'home/results', locals: { tweets: @partial_results } ) %>");
    <% end %>
  <% else %>
    <% if params[:max_id].blank? %>
      $('#twitter-graph').empty();
      $('#twitter-results .list-group').empty().html("No Results Found");
    <% end %>
    $('#twitter-nav').empty();
  <% end %>
<% else %>
  $('#twitter-graph').empty();
  $('#twitter-results .list-group').empty().html("<%= @error %>");
  $('#twitter-nav').empty();
<% end %>

<% if params[:search].present? %>
$('#engine-results').empty().append("<%= escape_javascript(render partial: 'home/engine_results', locals: { query: params[:search], google_results: @google_results, google_page: @google_page }) %>")
<% else %>
$('#engine-results').empty()
<% end %>

$('#timer-container').empty();
<% unless @account.searchable %>
  $('#timer-container').data('time', '<%= "#{ @account.restart }" %>');
<% end %>
$('.loader').addClass('hidden');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitterApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">SRMS Project</a>
        </div>
          <ul class="nav navbar-nav pull-right">
            <% if @account.present? %>
              <p class="navbar-text"><%= "Welcome, #{@account.nickname}" %></p>
              <li><%= link_to 'Disconnect Account', terminate_account_sessions_path %></li>
            <% else %>
              <li><%= link_to 'Add Twitter Account', 'auth/twitter'%></li>
            <% end %>
          </ul>
      </div>
    </nav>
    <div class='container'>
      <% if flash['error'].present? %>
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <p><%= flash['error'] %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>